"""Command to add a virtual (system-generated) message to a conversation.

Virtual messages are messages generated by the system (not the LLM) such as:
- Introduction messages at the start of a proactive flow
- Completion messages at the end of a proactive flow
- Score reports
- System notifications

These are persisted as assistant messages but are not generated by LLM inference.
"""

from dataclasses import dataclass, field
from typing import Any

from neuroglia.core import OperationResult
from neuroglia.data.infrastructure.abstractions import Repository
from neuroglia.eventing.cloud_events.infrastructure.cloud_event_bus import CloudEventBus
from neuroglia.eventing.cloud_events.infrastructure.cloud_event_publisher import CloudEventPublishingOptions
from neuroglia.mapping import Mapper
from neuroglia.mediation import Command, CommandHandler, Mediator

from application.commands.command_handler_base import CommandHandlerBase
from domain.entities.conversation import Conversation, MessageStatus
from domain.models.message import MessageRole
from integration.models.conversation_dto import ConversationDto


@dataclass
class AddVirtualMessageCommand(Command[OperationResult[str]]):
    """Command to add a virtual (system-generated) message.

    Returns the message_id of the created message.
    """

    conversation_id: str
    content: str
    message_type: str = "virtual"  # Type hint for the message (virtual, intro, completion, report)
    metadata: dict[str, Any] | None = field(default_factory=dict)
    user_info: dict[str, Any] | None = None


class AddVirtualMessageCommandHandler(
    CommandHandlerBase,
    CommandHandler[AddVirtualMessageCommand, OperationResult[str]],
):
    """Handle adding a virtual message to a conversation.

    Virtual messages are system-generated content that should be displayed
    and persisted like regular assistant messages.
    """

    def __init__(
        self,
        mediator: Mediator,
        mapper: Mapper,
        cloud_event_bus: CloudEventBus,
        cloud_event_publishing_options: CloudEventPublishingOptions,
        conversation_repository: Repository[Conversation, str],
    ):
        super().__init__(
            mediator,
            mapper,
            cloud_event_bus,
            cloud_event_publishing_options,
        )
        self.conversation_repository = conversation_repository

    async def handle_async(self, request: AddVirtualMessageCommand) -> OperationResult[str]:
        """Handle add virtual message command."""
        command = request

        # Get the conversation
        conversation = await self.conversation_repository.get_async(command.conversation_id)
        if conversation is None:
            return self.not_found(ConversationDto, command.conversation_id)

        # Build metadata
        metadata = command.metadata or {}
        metadata["message_type"] = command.message_type
        metadata["virtual"] = True

        # Add as assistant message with metadata indicating it's virtual
        message_id = conversation.add_message(
            role=MessageRole.ASSISTANT,
            content=command.content,
            status=MessageStatus.COMPLETED,
            metadata=metadata,
        )

        # Save the conversation
        await self.conversation_repository.update_async(conversation)

        return self.ok(message_id)
