# MkDocs Docker image with all required plugins
# Based on squidfunk/mkdocs-material with additional plugins
FROM squidfunk/mkdocs-material:9.5

# Install additional plugins required by the project
RUN pip install --no-cache-dir \
    mkdocs-mermaid2-plugin
