"""Observability utilities and metrics."""

from .metrics import access_policies_activated  # Task metrics; Source metrics; SourceTool metrics; ToolGroup metrics; AccessPolicy metrics; Agent access resolution metrics; Tool execution metrics
from .metrics import (
    access_policies_deactivated,
    access_policies_defined,
    access_policies_deleted,
    access_policies_updated,
    access_policy_processing_time,
    agent_access_cache_hits,
    agent_access_cache_misses,
    agent_access_denied,
    agent_access_resolutions,
    agent_resolution_time,
    agent_tools_resolved,
    circuit_breaker_opens,
    source_processing_time,
    source_refresh_failures,
    sources_deleted,
    sources_refreshed,
    sources_registered,
    task_processing_time,
    tasks_completed,
    tasks_created,
    tasks_failed,
    token_exchange_cache_hits,
    token_exchange_cache_misses,
    token_exchange_count,
    token_exchange_errors,
    tool_execution_count,
    tool_execution_errors,
    tool_execution_time,
    tool_group_processing_time,
    tool_group_resolution_time,
    tool_group_selectors_added,
    tool_group_selectors_removed,
    tool_group_tools_added,
    tool_group_tools_excluded,
    tool_group_tools_included,
    tool_group_tools_removed,
    tool_groups_activated,
    tool_groups_created,
    tool_groups_deactivated,
    tool_groups_deleted,
    tool_groups_updated,
    tool_processing_time,
    tools_deleted,
    tools_deprecated,
    tools_disabled,
    tools_discovered,
    tools_enabled,
    upstream_request_count,
    upstream_request_time,
)

__all__ = [
    # Task metrics
    "tasks_created",
    "tasks_completed",
    "tasks_failed",
    "task_processing_time",
    # Source metrics
    "sources_registered",
    "sources_deleted",
    "sources_refreshed",
    "source_refresh_failures",
    "source_processing_time",
    # SourceTool metrics
    "tools_discovered",
    "tools_enabled",
    "tools_disabled",
    "tools_deleted",
    "tools_deprecated",
    "tool_processing_time",
    # ToolGroup metrics
    "tool_groups_created",
    "tool_groups_updated",
    "tool_groups_deleted",
    "tool_groups_activated",
    "tool_groups_deactivated",
    "tool_group_selectors_added",
    "tool_group_selectors_removed",
    "tool_group_tools_added",
    "tool_group_tools_removed",
    "tool_group_tools_excluded",
    "tool_group_tools_included",
    "tool_group_processing_time",
    "tool_group_resolution_time",
    # AccessPolicy metrics
    "access_policies_defined",
    "access_policies_updated",
    "access_policies_deleted",
    "access_policies_activated",
    "access_policies_deactivated",
    "access_policy_processing_time",
    # Agent access resolution metrics
    "agent_access_resolutions",
    "agent_access_cache_hits",
    "agent_access_cache_misses",
    "agent_tools_resolved",
    "agent_access_denied",
    "agent_resolution_time",
    # Tool execution metrics (Phase 5)
    "tool_execution_count",
    "tool_execution_errors",
    "tool_execution_time",
    "token_exchange_count",
    "token_exchange_errors",
    "token_exchange_cache_hits",
    "token_exchange_cache_misses",
    "circuit_breaker_opens",
    "upstream_request_count",
    "upstream_request_time",
]
