"""Files proxy controller for forwarding file requests to tools-provider.

This controller proxies /api/files/* requests from agent-host to tools-provider,
enabling file downloads from links generated by the agent.

Routes:
    /api/files/upload -> tools-provider /api/files/upload
    /api/files/{filename} -> tools-provider /api/files/{filename}
    /api/files/ -> tools-provider /api/files/
"""

import logging

import httpx
from classy_fastapi.decorators import delete, get, post
from fastapi import Depends, File, HTTPException, Request, Response, UploadFile, status
from neuroglia.dependency_injection import ServiceProviderBase
from neuroglia.mapping import Mapper
from neuroglia.mediation import Mediator
from neuroglia.mvc import ControllerBase

from api.dependencies import get_current_user
from application.settings import app_settings

log = logging.getLogger(__name__)

# Timeout for proxied requests
PROXY_TIMEOUT = 30.0


class FilesController(ControllerBase):
    """Controller that proxies /api/files/* requests to tools-provider.

    This enables file downloads from links generated by the agent,
    which use /api/files/{filename} format.
    """

    def __init__(self, service_provider: ServiceProviderBase, mapper: Mapper, mediator: Mediator):
        super().__init__(service_provider, mapper, mediator)
        self._tools_provider_url = app_settings.tools_provider_url

    async def _proxy_request(
        self,
        request: Request,
        path: str,
        method: str = "GET",
        user: dict | None = None,
    ) -> Response:
        """Proxy a request to tools-provider."""
        url = f"{self._tools_provider_url}{path}"

        headers = {}
        if auth_header := request.headers.get("Authorization"):
            headers["Authorization"] = auth_header
        if cookie := request.headers.get("Cookie"):
            headers["Cookie"] = cookie

        log.debug(f"Proxying {method} to {url}")

        try:
            async with httpx.AsyncClient(timeout=PROXY_TIMEOUT) as client:
                response = await client.request(method=method, url=url, headers=headers)

                # Build response with relevant headers
                response_headers = {}
                for header in ["Content-Type", "Content-Disposition", "X-File-Expires", "X-File-Temporary"]:
                    if value := response.headers.get(header):
                        response_headers[header] = value

                return Response(
                    content=response.content,
                    status_code=response.status_code,
                    headers=response_headers,
                )
        except httpx.TimeoutException:
            raise HTTPException(status_code=status.HTTP_504_GATEWAY_TIMEOUT, detail="Request to tools-provider timed out")
        except httpx.RequestError as e:
            log.error(f"Proxy request failed: {e}")
            raise HTTPException(status_code=status.HTTP_502_BAD_GATEWAY, detail=f"Failed to connect to tools-provider: {str(e)}")

    @post(
        "/upload",
        summary="Upload a file to workspace",
        description="Forwards file uploads to tools-provider /api/files/upload",
    )
    async def upload_file(
        self,
        request: Request,
        file: UploadFile = File(...),
        user: dict = Depends(get_current_user),
    ) -> Response:
        """Proxy file upload to tools-provider."""
        content = await file.read()
        url = f"{self._tools_provider_url}/api/files/upload"

        headers = {}
        if auth_header := request.headers.get("Authorization"):
            headers["Authorization"] = auth_header
        if cookie := request.headers.get("Cookie"):
            headers["Cookie"] = cookie

        log.debug(f"Proxying file upload to {url}, file: {file.filename}, size: {len(content)}")

        try:
            async with httpx.AsyncClient(timeout=PROXY_TIMEOUT) as client:
                files = {"file": (file.filename, content, file.content_type or "application/octet-stream")}
                response = await client.post(url=url, files=files, headers=headers)

                return Response(
                    content=response.content,
                    status_code=response.status_code,
                    headers={"Content-Type": response.headers.get("Content-Type", "application/json")},
                )
        except httpx.TimeoutException:
            raise HTTPException(status_code=status.HTTP_504_GATEWAY_TIMEOUT, detail="File upload timed out")
        except httpx.RequestError as e:
            log.error(f"File upload proxy failed: {e}")
            raise HTTPException(status_code=status.HTTP_502_BAD_GATEWAY, detail=f"Failed to upload file: {str(e)}")

    @get(
        "/",
        summary="List files in workspace",
        description="Forwards request to tools-provider /api/files/",
    )
    async def list_files(
        self,
        request: Request,
        user: dict = Depends(get_current_user),
    ) -> Response:
        """Proxy list files request to tools-provider."""
        return await self._proxy_request(request=request, path="/api/files/", method="GET", user=user)

    @get(
        "/{filename:path}",
        summary="Download a file from workspace",
        description="Forwards download request to tools-provider /api/files/{filename}",
    )
    async def download_file(
        self,
        filename: str,
        request: Request,
        user: dict = Depends(get_current_user),
    ) -> Response:
        """Proxy file download request to tools-provider."""
        return await self._proxy_request(request=request, path=f"/api/files/{filename}", method="GET", user=user)

    @delete(
        "/{filename:path}",
        summary="Delete a file from workspace",
        description="Forwards delete request to tools-provider /api/files/{filename}",
    )
    async def delete_file(
        self,
        filename: str,
        request: Request,
        user: dict = Depends(get_current_user),
    ) -> Response:
        """Proxy file delete request to tools-provider."""
        return await self._proxy_request(request=request, path=f"/api/files/{filename}", method="DELETE", user=user)
